In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:/Users/User/Desktop/DA/BI/Sample - Superstore.csv',  encoding='latin1')

In [3]:
data.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7444,7445,CA-2017-127474,2/3/2017,2/7/2017,Second Class,RD-19810,Ross DeVincentis,Home Office,United States,Chicago,...,60610,Central,OFF-PA-10001166,Office Supplies,Paper,Xerox 2,5.184,1,0.2,1.8144
7333,7334,CA-2015-125563,4/11/2015,4/17/2015,Standard Class,PR-18880,Patrick Ryan,Consumer,United States,Tampa,...,33614,South,FUR-FU-10001290,Furniture,Furnishings,Executive Impressions Supervisor Wall Clock,67.360,2,0.2,10.1040
76,77,US-2017-118038,12/9/2017,12/11/2017,First Class,KB-16600,Ken Brennan,Corporate,United States,Houston,...,77041,Central,FUR-FU-10000260,Furniture,Furnishings,"6"" Cubicle Wall Clock, Black",9.708,3,0.6,-5.8248
1023,1024,CA-2015-167269,6/16/2015,6/20/2015,Standard Class,PB-19150,Philip Brown,Consumer,United States,Philadelphia,...,19134,East,OFF-EN-10003072,Office Supplies,Envelopes,Peel & Seel Envelopes,6.208,2,0.2,2.1728
6215,6216,CA-2015-161711,11/28/2015,12/3/2015,Standard Class,MC-17425,Mark Cousins,Corporate,United States,New York City,...,10035,East,FUR-FU-10000087,Furniture,Furnishings,"Executive Impressions 14"" Two-Color Numerals W...",68.160,3,0.0,27.9456

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [9]:
data.duplicated().sum()

0

In [11]:
data[['Order Date', 'Ship Date']] = data[['Order Date', 'Ship Date']].apply(pd.to_datetime)

In [13]:
data[['Ship Mode', 'Segment', 'Category', 'Sub-Category']] = data[['Ship Mode', 'Segment', 'Category', 'Sub-Category']].astype('category')

In [15]:
data.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [19]:
!pip install psycopg2-binary
from sqlalchemy import create_engine

Requirement already satisfied: psycopg2-binary in e:\anaconda\lib\site-packages (2.9.11)

In [20]:
# Подключение к PostgreSQL
engine = create_engine('postgresql+psycopg2://postgres:admin@localhost:5432/Superstore')

In [23]:
# Загружаем данные в таблицу superstore
data.to_sql('superstore', engine, if_exists='replace', index=False)

994

In [24]:
# Split the Dataset
initial_load = data.copy()
initial_load['Order Line ID'] = np.arange(len(initial_load))+1
# initial_load.to_csv(r'C:/Users/User/Desktop/DA/BI/loads/initial_load.csv', index=False)

In [27]:
secondary = initial_load.sample(500).copy().reset_index(drop=True)

In [29]:
# change customer last name SCD1
secondary.loc[:8, 'Customer Name'] = secondary.loc[:8, 'Customer Name'].apply(
    lambda x: x.split()[0] + ' Changed Last Name' if len(x.split())>1 else x
)

# change customer city SCD1
secondary.iloc[-5:, secondary.columns.get_loc('City')] = 'Another city'

# change postal code SCD1
secondary.loc[120:150, 'Postal Code'] = 999999

# defining the relationship between categories and subcategories
category_pairs = pd.DataFrame(np.unique(secondary[['Category', 'Sub-Category']].to_records(index=False)))

secondary['Sub-Category'] = np.where(secondary['Sub-Category']=='Bookcases', 'Category Redefining', secondary['Sub-Category'])

In [31]:
# scd2 simulation
new_rows = secondary.sample(50).copy().reset_index(drop=True)

new_rows.loc[new_rows.index[:5], ['City', 'State', 'Region']]=pd.DataFrame({
    'City': ['New City']*5, 
    'State': ['New State']*5,
    'Region': ['New Region']*5
}, index=new_rows.index[:5])

new_rows['Order Date'] = new_rows['Order Date']+pd.Timedelta(days=3)

# secondary['Row Status'] = 0
secondary = pd.concat([secondary, new_rows], ignore_index=True)

# secondary.loc[secondary.groupby(['Order ID', 'Product Name', 'Row ID'])['Order Date'].idxmax(), 'Row Status'] = 1

In [33]:
# change the row statuses for SCD2 based on the relevance of the date

def set_row_status(df, group_cols = ['Order ID', 'Product Name', 'Order Line ID'], date_col = 'Order Date'):
    df['Row Status'] = 0
    df.loc[df.groupby(group_cols)[date_col].idxmax(), 'Row Status']=1
    return df

initial_load = set_row_status(initial_load)
secondary = set_row_status(secondary)
np.where(secondary['Row Status']==0)

# secondary.sample(5)

(array([  2,   9,  16,  27,  37,  38,  44,  49,  53,  59,  64,  67,  76,
        101, 116, 120, 133, 188, 201, 224, 225, 227, 233, 240, 257, 272,
        282, 286, 288, 293, 295, 313, 329, 335, 351, 352, 366, 375, 401,
        413, 416, 432, 437, 439, 453, 460, 467, 479, 482, 498], dtype=int64),)

In [35]:
# Stage Layer

initial_load.to_sql('schema_superstore', engine, schema='stage', if_exists='replace', index=False)
secondary.to_sql('schema_superstore', engine, schema='stage', if_exists='append', index=False)

550

In [37]:
# Take the data from Stage and work with it
stage_table = pd.read_sql("""SELECT * FROM stage.schema_superstore WHERE "Row Status"=1""", con=engine)
stage_table.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Line ID,Row Status
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,1,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,2,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714,3,1

In [39]:
# Customer table 
customer_table = stage_table[['Customer ID', 'Customer Name', 'Segment']].copy()
customer_table = customer_table.drop_duplicates(subset='Customer ID')
# customer_table.to_sql('customer', engine, schema='core', if_exists='append', index=False)

In [41]:
# Category table

category_table = stage_table[['Category', 'Sub-Category']].copy().drop_duplicates()
category_table['Category ID'] = np.arange(len(category_table)) + 1
category_table = category_table[['Category ID', 'Category', 'Sub-Category']]
# category_table.to_sql('category', engine, schema='core', if_exists='append', index=False)

In [43]:
# Geo table

geo_table = stage_table[['Country', 'State', 'Region', 'City', 'Postal Code']].copy().drop_duplicates()
geo_table['Address ID'] = np.arange(len(geo_table))+1
geo_table = geo_table[['Address ID', 'Country', 'State', 'Region', 'City', 'Postal Code']]
# geo_table.to_sql('geo', engine, schema='core', if_exists='append', index=False)

In [45]:
# Product table 

product_table = stage_table[['Product ID', 'Product Name', 'Category', 'Sub-Category']].copy().drop_duplicates(subset='Product ID')

product_table = product_table.merge(
    category_table,
    on = ['Category', 'Sub-Category'],
    how='left'
)

product_table = product_table[['Product ID', 'Category ID', 'Product Name']]

# product_table.to_sql('product', engine, schema='core', if_exists='append', index=False)

In [49]:
# orders table 

order_table = stage_table[['Order ID', 'Customer ID', 'Order Date', 'Ship Date', 'Ship Mode', 'City', 'Postal Code']].copy()

order_table = order_table[order_table['Customer ID'].isin(customer_table['Customer ID'])]
order_table = order_table.drop_duplicates(subset=['Order ID', 'Customer ID', 'Order Date', 'Ship Date', 'Ship Mode'])

order_table = order_table.merge(
    geo_table,
    on=['City', 'Postal Code'], 
    how='left'
)

order_table = order_table[['Order ID', 'Customer ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Address ID']].sort_values(['Order ID', 'Order Date'])

order_table = order_table.drop_duplicates(subset='Order ID', keep='last')

# order_table.to_sql('orders', engine, schema='core', if_exists='append', index=False)

In [109]:
# Fact table Order Details
orderdetails_table = stage_table[['Order ID', 'Product ID', 'Quantity', 'Sales', 'Profit', 'Discount']] \
                        .copy() \
                        .groupby(['Order ID', 'Product ID'], as_index=False) \
                        .agg({'Quantity':'sum', 
                              'Sales' : 'sum', 
                              'Profit': 'sum',
                              'Discount':'mean'})

orderdetails_table = orderdetails_table[orderdetails_table['Order ID'].isin(order_table['Order ID'])]
orderdetails_table = orderdetails_table[orderdetails_table['Product ID'].isin(product_table['Product ID'])]

# orderdetails_table.to_sql('orderdetails', engine, schema='core', if_exists='append', index=False)

In [125]:
# Mart schema 

mart_table = orderdetails_table \
                .merge(order_table, on='Order ID', how='left') \
                .merge(product_table, on='Product ID', how='left') \
                .merge(category_table, on='Category ID', how='left') \
                .merge(geo_table, on='Address ID', how='left') \
                .merge(customer_table, on='Customer ID', how='left')

mart_table = mart_table[['Order ID', 'Product ID', 'Sales', 'Quantity', 'Category', 'Sub-Category', 'Customer Name', 'City']]

In [131]:
mart_table.to_sql('sales_data', engine, schema='mart', if_exists='append', index=False)

986